### ISSUE TITLE
Nodes 'Relay / hour' is not right while node is running less than 3600 seconds.

### ISSUE THREAD

**Issue by sbilly** [AL-dot-debug/nWatch#2]
Nodes 'Relay / hour' is not right while node is running less than 3600 seconds.

https://github.com/AL-dot-debug/nWatch/blob/main/functions.php#L427

```php
$return['nodes'][$ip]['relayperhour'] = perso_round($node['result']['relayMessageCount'], 0 );
```

should be

```php
$return['nodes'][$ip]['relayperhour'] = perso_round($node['result']['relayMessageCount']/$node['result']['uptime']*3600, 0 );
```

**Comment by AL-dot-debug** [comment]
Hello, the 

`$return['nodes'][$ip]['relayperhour'] = perso_round($node['result']['relayMessageCount'], 0 );`

case appears only if the node uptime is under 1 hour 


Best,
